name: Deploy midxfrontend
on:
  push:
    branches: [ecs-prod]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          path: '.'

      - name: Build and Deploy
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh
        env:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
